# Generated by Django 5.0.6 on 2024-06-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created_by",
            new_name="user",
        ),
    ]
