# Generated by Django 5.0.6 on 2024-06-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_notes", "0004_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
